name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change to your default branch if not 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t shobana29/hello-action-demo:latest .

      - name: Push Docker image
        run: |
          docker push shobana29/hello-action-demo:latest
